# Generated by Django 2.1.7 on 2019-05-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20190513_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
