# Generated by Django 2.1.7 on 2019-04-05 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
