# Generated by Django 2.1.7 on 2019-05-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20190514_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='weekday',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
