# Generated by Django 2.1.7 on 2019-05-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20190516_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='weekday',
        ),
    ]
