# Generated by Django 2.1.7 on 2019-05-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_remove_ticket_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='weekday',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
