# Generated by Django 2.1.7 on 2019-05-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20190516_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='weekday_word',
            new_name='weekday',
        ),
    ]
